//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelManageIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControl
    {
        public string AccessID { get; set; }
        public string RoleID { get; set; }
        public string ElementID { get; set; }
        public string CreateFlag { get; set; }
        public string ReadFlag { get; set; }
        public string UpdateFlag { get; set; }
        public string DeleteFlag { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual UIElement UIElement { get; set; }
        public virtual Role Role { get; set; }
    }
}
