//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelManageIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIElement
    {
        public UIElement()
        {
            this.AccessControls = new HashSet<AccessControl>();
        }
    
        public string ElementID { get; set; }
        public string ScreenName { get; set; }
        public string ElementName { get; set; }
    
        public virtual ICollection<AccessControl> AccessControls { get; set; }
    }
}
