//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelManageIT.Models
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public User()
        {
            this.User1 = new HashSet<User>();
            this.Opportunities = new HashSet<Opportunity>();
            this.Customers = new HashSet<Customer>();
            this.Contacts = new HashSet<Contact>();
            this.AccessControls = new HashSet<AccessControl>();
        }

        public string UserId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string RoleID { get; set; }
        public string EmployeeId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Company { get; set; }
        public string Theme { get; set; }
        public string IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string CreatedBy { get; set; }
        public string Gender { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<AccessControl> AccessControls { get; set; }
    }
}
