//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelManageITService
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign
    {
        public string campaignID { get; set; }
        public string CampaignName { get; set; }
        public string CampaignOwner { get; set; }
        public string CampaignType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Budget { get; set; }
        public string ActualCost { get; set; }
        public string ExpectedRevenue { get; set; }
        public string ExpectedResponse { get; set; }
        public string IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
