//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelManageITService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        public string COMPANYID { get; set; }
        public string COMPANYNAME { get; set; }
        public string DATABASE { get; set; }
    }
}
