//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelManageITService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.AccessControls = new HashSet<AccessControl>();
            this.Users = new HashSet<User>();
        }
    
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string IsActive { get; set; }
    
        public virtual ICollection<AccessControl> AccessControls { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
